name: 'user-web'
port: 8021
user_srv:
  host: '127.0.0.1'
  port: 50051
jwt:
  key: 'hellwoddsacxzcxzwq'
sms:
  key: 'LTAI5tEsjQGq12fFoGEF5yz6'
  secret: 'q2a1UCOXoD71fw0ANM99PxgPcFYPIZ'
redis:
  host: '127.0.0.1'
  port: 6379